### ISSUE TITLE
can't resovle rest-api-spring-boot-starter-jar!

### ISSUE THREAD

**Issue by 1713612859** [coder-amiao/rest-api-spring-boot-starter#1]
When I create a new module, then import this dependency, and refresh the project with Maven tools, this message is displayed ` can't resovle rest-api-spring-boot-starter-jar!` . So hope you can done finish; but It does not affect the use of.

**Comment by coder-amiao** [comment]
You can download the latest version1.4.1

**Comment by coder-amiao** [comment]
> When I create a new module, then import this dependency, and refresh the project with Maven tools, this message is displayed ` can't resovle rest-api-spring-boot-starter-jar!` . So hope you can done finish; but It does not affect the use of.


you can read https://boot.soboys.cn/simplest/ docs
